name: Validate

on:
  push:
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: "0 0 * * *"

jobs:
  hacs:
    run-name: "HACS validation"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hacs/action@main"
        with:
          category: "integration"
  hassfest:
    run-name: "hassfest validation"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: home-assistant/actions/hassfest@master
